#!/bin/bash

cp cam1/*.bmp .

for X in *.bmp
do
 montage cam1/"$X" cam2/"$X" cam3/"$X" cam4/"$X" -geometry 400x300+0+0 "$X"
 mogrify -format PNG "$X"
 rm "$X"
done

mencoder 'mf://*.PNG' -mf w=800:h=600:fps=10 -ovc lavc -lavcopts vcodec=msmpeg4 -oac copy -o output.avi




